### ISSUE TITLE
DFS-free radio

### ISSUE THREAD

**Issue by httpstorm** [dr-ni/openwrt-wrt3200acm-de#1]
Hello @dr-ni !
Please create a new branch or preferably invite me as a collaborator from settings!
A branch can be rebased when you update the master. We should not modify the master, because you won't be able to fast forward it to upstream.
https://github.com/httpstorm/openwrt/tree/dr-ni

**Comment by dr-ni** [comment]
Hi Georgi,
welcome here :-)
I've invited you.
Cheers, Uwe

**Comment by httpstorm** [comment]
Hallo Uwe! Enjoy!
I added all commits, so you can test and keep those you need. Important note about _wrt3200acm: reverted to network switch, instead of DSA_: if you restore your old `/etc/config/network`, make sure to add `lan` to your network `ifname`, otherwise the router will only be accessible over Wi-Fi. See the commit description.

```
# original
config interface 'lan'
	option ifname 'lan1 lan2 lan3 lan4'

# revert to network switch
config interface 'lan'
	option ifname 'lan'

# universal
config interface 'lan'
	option ifname 'lan lan1 lan2 lan3 lan4'
```

**Comment by httpstorm** [comment]
Please remove the comments under the public thread that will not be useful to others!

**Comment by dr-ni** [comment]
thank you, I'll try it :-)
I've removed all from the thread - you should also all answers now

**Comment by dr-ni** [comment]
have now renamed the branch gvalkov to country_unlocked
see also the new issue ; -)

**Comment by dr-ni** [comment]
have now default lan in /etc/config/network
config interface 'lan'
        option type 'bridge'
        option ifname 'lan.1'
        option proto 'static'
        option ipaddr '192.168.1.1'
        option netmask '255.255.255.0'
        option ip6assign '60'


old was:
config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'xxxx:xxxx:xxxx::/48'

config interface 'lan'
	option type 'bridge'
	option ifname 'eth0.1'
	option proto 'static'
	option netmask '255.255.255.0'
	option ip6assign '60'
	option ipaddr '192.168.2.1'

config interface 'wan'
	option ifname 'eth1.2'
	option proto 'static'
	option netmask '255.255.0.0'
	option ipaddr '192.168.0.3'
	option gateway '192.168.0.1'
	list dns '1.1.1.1'

config interface 'wan6'
	option ifname 'eth1.2'
	option proto 'dhcpv6'

config switch
	option name 'switch0'
	option reset '1'
	option enable_vlan '1'

config switch_vlan
	option device 'switch0'
	option vlan '1'
	option ports '0 1 2 3 5t'

config switch_vlan
	option device 'switch0'
	option vlan '2'
	option ports '4 6t'

config interface 'guest'
	option type 'bridge'
	option proto 'static'
	option ipaddr '192.168.3.1'
	option netmask '255.255.255.0'

config interface 'broadband'
	option device '/dev/ttyUSB0'
	option apn 'internet.eplus.de'
	option username 'eplus'
	option password 'internet'
	option service 'umts'
	option proto '3g'
	option dialnumber '*99#'
	option ipv6 'auto'
	option auto '0'

config interface 'LTE_hilink'
	option proto 'dhcp'
	option auto '0'
	option ifname 'eth2'


what do I have to change?

**Comment by httpstorm** [comment]
Auto: use LuCI on a blank on the default config.
Manual: Use `lan` as the lan ports, and `wan` as the wan ports. If you need to have VLANS, then use `lan.1, lan.2` etc.

```
eth0.1 → lan or lan.1 if you need VLANS, where 1 is VLAN 1
eth1.2 → wan or wan.2 if you need VLANS, where 2 is VLAN 2
```

Also edit the switch section: `t` means tagging and must be set if you use VLAN. Skip it if you don't.
```
option ports '0 1 2 3 5'
option ports '4 6'

option ports '0 1 2 3 5t'
option ports '4 6t'

0-3 LAN ports
4 WAN port
5 CPU0
6 CPU1

5t CPU0 when using VLAN
6t CPU1 when using VLAN
```

**Comment by dr-ni** [comment]
I think I'll throw out the network switch revert commit, actually I need first to get it running with my backup config.
How can I disable a commit?

**Comment by httpstorm** [comment]
You can checkout the commit before that, since this is the last one. Note that your configuration is very old, even before the network switch was originally removed, so it will not work with or without this commit. It is safer to start blank or follow the instructions to migrate. Otherwise you have to access the router over Wi-Fi or UART. If anything goes wrong:
(power on, wait 10 seconds, power off) repeat 3 times and the old firmware will boot.
